In [ ]:
import numpy as np

In [ ]:
np.arange(6,78,6)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72])

In [ ]:
np.arange()

1. Write a function that asks the user for dimentions of a matrix of integer numbers as well as the range of the numbers and creates it:

In [ ]:
def func_1():
  r=int(input(' What is row size do you want?'))
  c=int(input('What col size do you want?'))
  mini=int(input('Whats your minimum range'))
  maxi=int(input('Whats your minimum range'))

  mat=np.random.randint(r,c,(mini,maxi))

  return(mat)



2. Repeat exercise 1, but without user input

In [ ]:
def func_2(r,c,mini,maxi):
  mat=np.random.randint(r,c,(mini,maxi))

  return(mat)


3. Repeat exercise 2, but this time, have the matrix saved in memory

In [ ]:

def func_3(r,c,mini,maxi):
  mat=np.random.randint(r,c,(mini,maxi))

  return(mat)
  #print(mat)



In [ ]:
k=func_3(3,5,3,10)

In [ ]:
k

array([[4, 4, 3, 3, 3, 3, 3, 4, 3, 3],
       [4, 4, 4, 3, 3, 4, 3, 3, 3, 3],
       [3, 4, 4, 3, 3, 3, 3, 3, 3, 4]])

In [ ]:
type(k)

numpy.ndarray

4. Write a function that takes in a SQUARE matrix, otherwise, report not valid, then reports on its shape, and outputs the diagonal elements of the matrix

In [ ]:
def func_4(mat):
    r,c=mat.shape
    k=[]
    if r==c:
      for i in range (r):
        k.append(mat[i,i])
      return(k)

    else:
      print('Wrong Shape')







In [ ]:
d=np.random.randint(0,10,(6,6))

In [ ]:
d

array([[5, 9, 4, 6, 4, 5],
       [7, 6, 8, 6, 2, 8],
       [1, 4, 9, 9, 6, 7],
       [0, 6, 2, 1, 2, 5],
       [1, 2, 0, 9, 2, 2],
       [1, 8, 4, 6, 7, 2]])

In [ ]:
func_4(d)

[5, 6, 9, 1, 2, 2]

Alternatively

In [ ]:
def func_4(mat):
    print(mat.shape)
    return np.diag(mat)

5. Write a function that takes in a list of numbers and creates a matrix which has these values in its diagonal and value of 5 in all other positions

In [ ]:
def func_5(dia):
  l=len(dia)

  dia=np.array(dia)

  mat=np.zeros([l,l])+5

  for i in range (mat.shape[0]):
    mat[i,i]=dia[i]

  return (mat)


In [ ]:
func_5([2,4,6])

array([[2., 5., 5.],
       [5., 4., 5.],
       [5., 5., 6.]])

##Alternatively

In [ ]:
np.diag([2,4,6])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 6]])

6. Write a function, that performs a dot product between to vectors

In [ ]:
def funci_6(a,b):

  if a.shape[0]==b.shape[0]:
     k=[]

     for i in range(a.shape[0]):
       temp=a[i]*b[i]

       k.append(temp)

     return (sum(k))

  else:

    print('out of shape')






In [ ]:
vec_1=np.array([9,2,3,4,6])

vec_2=np.array([1,3,9,5,6])

In [ ]:
funci_6(vec_1,vec_2)

98

##Alternatively

In [ ]:
np.dot(vec_1,vec_2)

98